---
title: Python Quick Reaction Game
hero_image: images/banner.png
description: Make a quick reaction game to play with your friends
original_url: https://raspberrypi.org/learning/python-quick-reaction-game
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-2, manufacture-0, community-0
interests: games
technologies: electronic-components, python
site_areas: projects
hardware: electronic-components
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Building the circuit
- title: Controlling the light
  completion:
  - engaged
- title: Adding an element of surprise
- title: Detecting the buttons
- title: Get player names
  completion:
  - internal
  completion:
  - external